INSERT INTO categories_t (name)
VALUES ('ГОЛОВНЫЕ УБОРЫ'),
       ('ОДЕЖДА'),
       ('ОБУВЬ'),
       ('СУМКИ'),
       ('АКСЕССУАРЫ'),
       ('ТВОРЧЕСТВО');

INSERT INTO brands_t (name)
VALUES ('KANGOL'),
       ('PROCLUB'),
       ('NOVESTA'),
       ('PHAT');

INSERT INTO items_t (model, amount, size, color, sex, price, brand_id, category_id)
VALUES ('FURGORA NEW WAVE LAHINCH', 12, 'L', 'ЗЕЛЕНЫЙ', 'UNISEX', 12300, 1, 1),
       ('FURGORA POP STRIPE CASUAL', 2, 'S', 'ЧЕРНЫЙ', 'UNISEX', 13500, 1, 1),
       ('BIRDSEYE MAZE BIN', 13, 'L', 'ЧЕРНЫЙ', 'UNISEX', 11250, 1, 1),
       ('WOOLY FLORAL CASUAL', 14, 'M', 'КРАСНЫЙ', 'UNISEX', 11050, 1, 1),
       ('CHECK QUILT BUCKET', 13, 'M', 'БЕЖЕВЫЙ', 'UNISEX', 9500, 1, 1),
       ('COORDINATES MASK BERET', 9, 'L', 'ЧЕРНЫЙ', 'UNISEX', 9750, 1, 1),
       ('PREPPY JAX BERET', 11, 'L', 'БЕЖЕВЫЙ', 'UNISEX', 9300, 1, 1),
       ('TWIST STRIPE BEANIE', 0, 'M', 'БЕЖЕВЫЙ', 'UNISEX', 8450, 1, 1),
       ('POMPOM BEANIE', 5, 'L', 'БЕЛЫЙ', 'UNISEX', 8500, 1, 1),
       ('WOOL AVIATOR', 13, 'M', 'ЗЕЛЕНЫЙ', 'UNISEX', 11200, 1, 1),
       ('CABLE BEANIE', 19, 'M', 'ЧЕРНЫЙ', 'UNISEX', 6750, 1, 1),
       ('Y2K BALACLAVA', 14, 'M', 'КРАСНЫЙ', 'UNISEX', 6300, 1, 1),
       ('CHECK QUILT 4 PANEL CAP', 1, 'S', 'БЕЖЕВЫЙ', 'UNISEX', 8800, 1, 1),
       ('FLEXFIT FLAT PEAK BB', 4, 'M', 'БЕЛЫЙ', 'UNISEX', 8400, 1, 1),
       ('GADGET 504', 0, 'S', 'ЗЕЛЕНЫЙ', 'UNISEX', 9750, 1, 1),
       ('Heavyweight Cotton Short Sleeve Crew Neck T-Shirt', 10, 'XS', 'ЗЕЛЕНЫЙ', 'UNISEX', 765, 2, 2),
       ('Pro Club Men''s Comfort Cotton Short Sleeve T-Shirt', 16, 'XS', 'ЗЕЛЕНЫЙ', 'UNISEX', 595, 2, 2),
       ('Pro Club Men''s Heavyweight Cotton Long Sleeve Crew Neck T-Shirt', 8, 'S', 'КРАСНЫЙ', 'UNISEX', 990, 2, 2),
       ('Heavyweight Basic Hoodie', 16, 'M', 'БЕЛЫЙ', 'UNISEX', 4400, 2, 2),
       ('Heavyweight Basic Sweat Pants', 1, 'M', 'КРАСНЫЙ', 'UNISEX', 3500, 2, 2),
       ('Comfort Bomber Jacket', 6, 'M', 'ЗЕЛЕНЫЙ', 'UNISEX', 5400, 2, 2),
       ('Comfort Tech Wide Leg Flare Pant', 4, 'XS', 'ЧЕРНЫЙ', 'UNISEX', 4680, 2, 2),
       ('Comfort Polar Fleece Cargo Pants', 8, 'S', 'ЧЕРНЫЙ', 'UNISEX', 4860, 2, 2),
       ('Heavyweight Flannel Shirt Jacket', 6, 'XL', 'БЕЛЫЙ', 'UNISEX', 5940, 2, 2),
       ('Heavyweight Stretch Twill Cargo Lounge Pant', 16, 'XL', 'ЗЕЛЕНЫЙ', 'UNISEX', 5040, 2, 2),
       ('Heavyweight Pullover Hoodie (13oz)', 13, 'L', 'ЧЕРНЫЙ', 'UNISEX', 3330, 2, 2),
       ('Heavyweight Corduroy Chore Jacket', 8, 'XL', 'КРАСНЫЙ', 'UNISEX', 6480, 2, 2),
       ('Heavyweight Corduroy Carpenter Pant', 2, 'XS', 'ЗЕЛЕНЫЙ', 'UNISEX', 5310, 2, 2),
       ('New Era 5950 Fitted Heavyweight Champions Box Logo Hat', 19, 'L', 'КРАСНЫЙ', 'UNISEX', 4300, 2, 2),
       ('Heavyweight Work Vest', 11, 'XL', 'БЕЖЕВЫЙ', 'UNISEX', 5400, 2, 2),
       ('Star Master Cord Dark Grey Grey', 18, '37', 'БЕЛЫЙ', 'UNISEX', 6900, 3, 3),
       ('Star Master Mustard Transparent', 0, '38', 'БЕЛЫЙ', 'UNISEX', 6100, 3, 3),
       ('Star Master Brown-White Ecru', 10, '38', 'БЕЛЫЙ', 'UNISEX', 6500, 3, 3),
       ('Star Dribble Beige Sedlova', 13, '41', 'КРАСНЫЙ', 'UNISEX', 6800, 3, 3),
       ('Star Master Cord Beige/Wheat', 7, '41', 'БЕЖЕВЫЙ', 'UNISEX', 6900, 3, 3),
       ('Star Master All Black', 18, '39', 'ЗЕЛЕНЫЙ', 'UNISEX', 5900, 3, 3),
       ('Star Master Military Transparent', 2, '38', 'ЧЕРНЫЙ', 'UNISEX', 6900, 3, 3),
       ('Star Master Beige', 16, '44', 'ЧЕРНЫЙ', 'UNISEX', 6100, 3, 3),
       ('Star Master White-Grey White', 14, '38', 'ЗЕЛЕНЫЙ', 'UNISEX', 6900, 3, 3),
       ('Star Dribble Beige Transparent', 5, '43', 'ЗЕЛЕНЫЙ', 'UNISEX', 7490, 3, 3),
       ('Star Dribble Cord Dark Grey Grey', 0, '38', 'БЕЖЕВЫЙ', 'UNISEX', 6900, 3, 3),
       ('Star Dribble White', 13, '44', 'БЕЛЫЙ', 'UNISEX', 6600, 3, 3),
       ('Marathon Trail Truffle Pine', 9, '39', 'ЧЕРНЫЙ', 'UNISEX', 15000, 3, 3),
       ('GAT White 003 Transparent', 3, '39', 'БЕЛЫЙ', 'UNISEX', 13800, 3, 3),
       ('Marathon Vegan Trail Olive', 10, '38', 'БЕЖЕВЫЙ', 'UNISEX', 15000, 3, 3);